name: flogged_example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lumberdash: ^2.1.1
  flogged:
    path: ..
  package_info: ^0.4.0+18
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
