name: flogged
description: Log to Logstash from Flutter applications using lumberdash
version: 1.0.1
author: Peter Bryant
homepage: https://github.com/netsells/flogged

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  lumberdash: ^3.0.0
